### ISSUE TITLE
Error after installing gluegun

### ISSUE THREAD

**Issue by skurtzemann** [minio/gluegun#34]
Hi,
After installing gluegun using `gem install gluegun` I got the following error

```
bash-4.4# ./bin/gluegun
Traceback (most recent call last):
	6: from ./bin/gluegun:3:in `<main>'
	5: from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	4: from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	3: from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	2: from /usr/local/bundle/gems/gluegun-0.1.2/lib/gluegun.rb:4:in `<top (required)>'
	1: from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- github/markdown (LoadError)
```

Any idea about the problem ?

Thanks

**Comment by kaankabalak** [comment]
Thanks for opening the issue! Could you try installing the github-markdown gem and try running it again? I had a similar error and solved it that way.

**Comment by deekoder** [comment]
We have to update the readme.

**Comment by deekoder** [comment]
@skurtzemann  i will fix this by adding this as a dependency gem. Until then please hand install with `gem install github-markdown` and then use gluegun.

**Comment by deekoder** [comment]
We also need to do `gem install github-markup`

**Comment by deekoder** [comment]
it should be fixed now @skurtzemann.
